---

plugins:
# https://github.com/jest-community/eslint-plugin-jest
  - jest

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true
  es2020: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: 0
  import/extensions: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]